### 1. 게시물 생성
POST {{base}}/posts/register
Content-Type: application/json

{
  "writerId": "usadev0813",
  "title": "테스트 제목",
  "content": "테스트 게시물 내용"
}

### 2. 게시물 전체 조회
GET {{base}}/posts
Content-Type: application/json

### 3. 게시물 단건 조회
GET {{base}}/posts/1
Content-Type: application/json